import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { TransformControls } from 'three/addons/controls/TransformControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const STORAGE_KEY='castorium.mapEditor.v1';
const DB_NAME='castorium-editor-assets';
const DB_STORE='blobs';
const COLORS={structure:0x657382,machine:0x7d8f72,vehicle:0x9a835b,product:0x8e684e,worker:0x7b6e91,hotspot:0xf0b95b,zone:0x557d8a,ui:0xa0697a,helper:0x7b7b7b};
const LAYERS=['structure','machine','vehicle','product','worker','hotspot','zone','ui','helper'];
const CATALOG={
  'Estructura':[ ['floor_marker','Marcador de piso','structure'],['wall','Pared','structure'],['column','Columna','structure'],['gate','Portón / acceso','structure'],['office','Bloque de oficina','structure'],['sector_sign','Cartel de sector','structure'],['camera_start','Cámara inicial','helper'],['camera_target','Target de cámara','helper'] ],
  'Máquinas':[ ['cut_line','Línea de corte','machine'],['cut_blade','Cuchilla de corte','machine'],['cut_line_broken','Línea de corte rota','machine'],['pack_table','Mesa de embalaje','machine'],['conveyor','Cinta transportadora','machine'],['pack_robot','Robot de embalaje','machine'],['artisan_line','Línea artesanal','machine'],['crane_bridge','Puente grúa','machine'],['crane_trolley','Trolley de grúa','machine'],['crane_hook','Gancho de grúa','machine'],['crane_sling','Eslinga procedural','helper'] ],
  'Vehículos':[ ['forklift','Autoelevador','vehicle'],['log_truck','Camión de troncos','vehicle'],['dispatch_truck','Camión de despacho','vehicle'] ],
  'Producto':[ ['raw_log','Tronco entero','product'],['cut_log','Tronco cortado','product'],['cut_stack','Pila de troncos','product'],['package','Paquete terminado','product'] ],
  'Personajes':[ ['beaver','Castor','worker'],['pack_robot_character','Robot personaje','worker'] ],
  'Buffers':[ ['buffer','Buffer paramétrico','zone'],['storage_area','Área de depósito','zone'] ],
  'Hotspots':[ ['work_point','Punto de trabajo','hotspot'],['maintenance_point','Punto mantenimiento','hotspot'],['pickup_point','Punto pickup','hotspot'],['drop_point','Punto drop','hotspot'],['idle_point','Punto idle','hotspot'],['accident_point','Punto accidente','hotspot'],['protest_point','Punto protesta','hotspot'],['quality_text_anchor','Anchor texto calidad','ui'],['machine_text_anchor','Anchor texto máquina','ui'],['blade_up','Cuchilla: arriba','hotspot'],['blade_down','Cuchilla: abajo','hotspot'] ],
};
const DYNAMIC_REFS=[
  ['custom','Posición custom'],
  ['cut1.outputFree','Corte 1 · salida libre'],['cut2.outputFree','Corte 2 · salida libre'],['cut3.outputFree','Corte 3 · salida libre'],
  ['cutBuffer.free','Depósito corte · slot libre'],['artisanBuffer.free','Depósito artesanal · slot libre'],['finishedBuffer.free','Producto terminado · slot libre'],
  ['pack1.inputFree','Embalaje 1 · entrada libre'],['pack2.inputFree','Embalaje 2 · entrada libre'],
  ['pack1.outputFree','Embalaje 1 · salida libre'],['pack2.outputFree','Embalaje 2 · salida libre'],
  ['dispatch.free','Camión despacho · slot libre'],
];

const $=s=>document.querySelector(s);
const viewport=$('#viewport');
const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; viewport.appendChild(renderer.domElement);
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x252b31);
const camera=new THREE.PerspectiveCamera(45,1,.05,1000); camera.position.set(18,20,22);
const orbit=new OrbitControls(camera,renderer.domElement); orbit.target.set(0,0,0); orbit.enableDamping=true;
const transform=new TransformControls(camera,renderer.domElement); transform.setSpace('world'); scene.add(transform);
transform.addEventListener('dragging-changed',e=>orbit.enabled=!e.value);
transform.addEventListener('objectChange',()=>{syncSelectedFromThree();queueSave();renderInspector();renderTree();});
scene.add(new THREE.HemisphereLight(0xffffff,0x4a5260,2.1)); const sun=new THREE.DirectionalLight(0xffffff,2.3);sun.position.set(12,25,8);scene.add(sun);
let grid=new THREE.GridHelper(60,60,0x7d8894,0x4b555f);scene.add(grid);
const floorGroup=new THREE.Group();floorGroup.name='__floor';scene.add(floorGroup);
const objectGroup=new THREE.Group();objectGroup.name='__objects';scene.add(objectGroup);
const routeGroup=new THREE.Group();routeGroup.name='__routes';scene.add(routeGroup);
const gltfLoader=new GLTFLoader(); const textureLoader=new THREE.TextureLoader();
const clock=new THREE.Clock();

let data=defaultData();
let selectedId=null,selectedThree=null,currentTileId=null,floorPaint=false,eraseFloorMode=false,axisLock=null;
let runtime=new Map(), mixers=new Map(), assetRuntime=new Map();

function defaultData(){return {version:1,gridSize:1,floor:{width:30,depth:20,cells:{}},objects:[],assets:[],tiles:[],routes:[],layers:Object.fromEntries(LAYERS.map(x=>[x,true])),camera:{position:[18,20,22],target:[0,0,0]}};}
function uid(prefix='id'){return prefix+'-'+Math.random().toString(36).slice(2,9);}
function transformData(){return {position:{x:0,y:0,z:0},rotation:{x:0,y:0,z:0},scale:{x:1,y:1,z:1}};}
function serializeTransform(obj){return {position:{x:+obj.position.x.toFixed(4),y:+obj.position.y.toFixed(4),z:+obj.position.z.toFixed(4)},rotation:{x:+obj.rotation.x.toFixed(5),y:+obj.rotation.y.toFixed(5),z:+obj.rotation.z.toFixed(5)},scale:{x:+obj.scale.x.toFixed(4),y:+obj.scale.y.toFixed(4),z:+obj.scale.z.toFixed(4)}};}
function applyTransform(obj,t){obj.position.set(t.position.x,t.position.y,t.position.z);obj.rotation.set(t.rotation.x,t.rotation.y,t.rotation.z);obj.scale.set(t.scale.x,t.scale.y,t.scale.z);}
function catalogInfo(kind){for(const [group,items] of Object.entries(CATALOG))for(const i of items)if(i[0]===kind)return {group,label:i[1],layer:i[2]};return {group:'Otros',label:kind,layer:'helper'};}

function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(DB_STORE);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function dbPut(key,val){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(val,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});}
async function dbGet(key){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(DB_STORE,'readonly');const r=tx.objectStore(DB_STORE).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}

function placeholder(kind){const layer=catalogInfo(kind).layer;let g=new THREE.Group();let mesh;
  if(layer==='hotspot'||layer==='ui'){mesh=new THREE.Mesh(new THREE.SphereGeometry(.18,12,8),new THREE.MeshBasicMaterial({color:COLORS[layer],depthTest:false}));g.add(mesh);const ring=new THREE.Mesh(new THREE.TorusGeometry(.3,.025,8,20),new THREE.MeshBasicMaterial({color:COLORS[layer],depthTest:false}));ring.rotation.x=Math.PI/2;g.add(ring);g.userData.editorHelper=true;return g;}
  if(kind==='storage_area'||kind==='buffer'){mesh=new THREE.Mesh(new THREE.BoxGeometry(2,.06,2),new THREE.MeshStandardMaterial({color:COLORS[layer],transparent:true,opacity:.38}));g.add(mesh);return g;}
  const geo=kind.includes('truck')?new THREE.BoxGeometry(3,1.4,1.5):kind==='forklift'?new THREE.BoxGeometry(1.4,1.1,1):kind==='wall'?new THREE.BoxGeometry(4,2.5,.18):kind==='column'?new THREE.BoxGeometry(.35,3,.35):new THREE.BoxGeometry(1.7,1,1.4);
  mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:COLORS[layer],roughness:.8}));mesh.position.y=geo.parameters?.height?geo.parameters.height/2:.5;g.add(mesh);return g;
}
function addLabelSprite(group,text){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle='#111c';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#fff';ctx.font='32px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,58);const tex=new THREE.CanvasTexture(c);const spr=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false}));spr.scale.set(3.2,.6,1);spr.position.y=1.6;group.add(spr);}
async function instantiateRecord(rec){const old=runtime.get(rec.id);if(old){objectGroup.remove(old);disposeObject(old);runtime.delete(rec.id);}let obj;
  if(rec.assetId){try{obj=await instantiateAsset(rec.assetId);}catch(e){console.warn(e);}}
  if(!obj)obj=placeholder(rec.kind);
  obj.userData.recordId=rec.id;obj.userData.kind=rec.kind;obj.visible=rec.visible!==false && data.layers[rec.layer]!==false;applyTransform(obj,rec.transform);objectGroup.add(obj);runtime.set(rec.id,obj);addLabelSprite(obj,rec.name);
  if(rec.kind==='buffer')refreshBufferVisual(rec);
  if(rec.kind==='crane_sling')refreshSling(rec);
  if(rec.animation)playAnimation(rec.id,rec.animation);
  return obj;
}
async function instantiateAsset(assetId){const asset=data.assets.find(a=>a.id===assetId);if(!asset)throw Error('asset missing');let proto=assetRuntime.get(assetId);if(!proto){const blob=await dbGet('model:'+assetId);if(!blob)throw Error('blob missing');const ab=await blob.arrayBuffer();const gltf=await new Promise((res,rej)=>gltfLoader.parse(ab,'',res,rej));proto={scene:gltf.scene,animations:gltf.animations};assetRuntime.set(assetId,proto);asset.animations=gltf.animations.map(a=>a.name);queueSave();}
  const clone=proto.scene.clone(true);clone.userData.editorAnimations=proto.animations;return clone;
}
function disposeObject(o){o.traverse(n=>{if(n.geometry)n.geometry.dispose?.();});}

function newRecord(kind,name){const info=catalogInfo(kind);return {id:uid(kind),kind,name:name||info.label,layer:info.layer,visible:true,assetId:null,transform:transformData(),meta:kind==='buffer'?{count:4,offset:{x:1.2,y:0,z:0},visualKind:'cut_stack'}:kind==='crane_sling'?{fromRef:null,toRef:null}: {},animation:null};}
async function addRecord(kind,name){const rec=newRecord(kind,name);data.objects.push(rec);await instantiateRecord(rec);selectRecord(rec.id);queueSave();renderTree();}
function deleteSelected(){if(!selectedId)return;const i=data.objects.findIndex(o=>o.id===selectedId);if(i<0)return;const obj=runtime.get(selectedId);if(obj){objectGroup.remove(obj);disposeObject(obj);}runtime.delete(selectedId);data.objects.splice(i,1);selectedId=null;selectedThree=null;transform.detach();queueSave();renderTree();renderInspector();}
function duplicateSelected(){const r=getSelected();if(!r)return;const c=structuredClone(r);c.id=uid(r.kind);c.name=r.name+' copia';c.transform.position.x+=data.gridSize;data.objects.push(c);instantiateRecord(c).then(()=>selectRecord(c.id));queueSave();renderTree();}
function getSelected(){return data.objects.find(o=>o.id===selectedId)||null;}
function selectRecord(id){selectedId=id;selectedThree=runtime.get(id)||null;if(selectedThree)transform.attach(selectedThree);renderTree();renderInspector();}
function syncSelectedFromThree(){const r=getSelected();if(r&&selectedThree){r.transform=serializeTransform(selectedThree);if(r.kind==='buffer')refreshBufferVisual(r);if(r.kind==='crane_sling')refreshSling(r);}}

function refreshBufferVisual(rec){const root=runtime.get(rec.id);if(!root)return;let group=root.getObjectByName('__bufferCopies');if(group){root.remove(group);disposeObject(group);}group=new THREE.Group();group.name='__bufferCopies';const count=Math.max(1,+rec.meta.count||1),off=rec.meta.offset||{x:1,y:0,z:0};for(let i=1;i<count;i++){const ghost=placeholder(rec.meta.visualKind||'cut_stack');ghost.scale.set(.55,.55,.55);ghost.position.set(off.x*i,off.y*i,off.z*i);ghost.traverse(n=>{if(n.material){n.material=n.material.clone();n.material.transparent=true;n.material.opacity=.5;}});group.add(ghost);}root.add(group);}
function resolveRecordRef(id){const r=data.objects.find(o=>o.id===id);return r?runtime.get(r.id):null;}
function refreshSling(rec){const root=runtime.get(rec.id);if(!root)return;root.clear();const from=resolveRecordRef(rec.meta.fromRef),to=resolveRecordRef(rec.meta.toRef);const a=from?from.getWorldPosition(new THREE.Vector3()):new THREE.Vector3(0,3,0);const b=to?to.getWorldPosition(new THREE.Vector3()):new THREE.Vector3(0,0,0);const dir=new THREE.Vector3().subVectors(b,a);const len=dir.length();const cyl=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,Math.max(.001,len),6),new THREE.MeshBasicMaterial({color:0xa9adb2}));cyl.position.copy(a).add(b).multiplyScalar(.5);cyl.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.clone().normalize());scene.attach(cyl);root.add(cyl);}

function renderTree(){const q=$('#treeFilter').value.toLowerCase();$('#sceneTree').innerHTML=data.objects.filter(o=>o.name.toLowerCase().includes(q)||o.kind.includes(q)).map(o=>`<div class="tree-item ${o.id===selectedId?'selected':''}" data-id="${o.id}"><button class="vis">${o.visible===false?'○':'●'}</button><span class="name">${o.name}</span><small>${catalogInfo(o.kind).label}</small></div>`).join('')||'<div class="muted">Escena vacía</div>';document.querySelectorAll('.tree-item').forEach(el=>{el.addEventListener('click',e=>{if(e.target.classList.contains('vis'))return;selectRecord(el.dataset.id);});el.querySelector('.vis').addEventListener('click',e=>{e.stopPropagation();const r=data.objects.find(x=>x.id===el.dataset.id);r.visible=r.visible===false;runtime.get(r.id).visible=r.visible&&data.layers[r.layer]!==false;queueSave();renderTree();});});}
function renderLayers(){$('#layerList').innerHTML=LAYERS.map(l=>`<div class="layer-row"><input type="checkbox" data-layer="${l}" ${data.layers[l]!==false?'checked':''}><span>${l}</span></div>`).join('');document.querySelectorAll('[data-layer]').forEach(el=>el.addEventListener('change',()=>{data.layers[el.dataset.layer]=el.checked;data.objects.filter(o=>o.layer===el.dataset.layer).forEach(o=>{const r=runtime.get(o.id);if(r)r.visible=el.checked&&o.visible!==false;});queueSave();}));}
function numInput(label,key,axis,val){return `<label>${label}</label><input class="tr" data-key="${key}" data-axis="${axis}" type="number" step="0.1" value="${(+val).toFixed(3)}">`;}
function renderInspector(){const r=getSelected();if(!r){$('#inspector').innerHTML='<div class="muted">Seleccioná un objeto.</div>';return;}const assets=data.assets.map(a=>`<option value="${a.id}" ${a.id===r.assetId?'selected':''}>${a.name}</option>`).join('');const anims=(data.assets.find(a=>a.id===r.assetId)?.animations||[]).map(n=>`<option ${n===r.animation?'selected':''}>${n}</option>`).join('');let special='';
  if(r.kind==='buffer')special=`<div class="inspector-block"><h4>Buffer paramétrico</h4><div class="kv"><span>Cantidad</span><input id="bufCount" type="number" min="1" max="20" value="${r.meta.count||1}"></div><div class="inspector-grid"><label>Offset</label><input class="bufOff" data-axis="x" type="number" step=".1" value="${r.meta.offset.x}"><input class="bufOff" data-axis="y" type="number" step=".1" value="${r.meta.offset.y}"><input class="bufOff" data-axis="z" type="number" step=".1" value="${r.meta.offset.z}"></div><div class="kv"><span>Visual</span><select id="bufVisual">${['cut_stack','raw_log','package','cut_log'].map(k=>`<option value="${k}" ${r.meta.visualKind===k?'selected':''}>${catalogInfo(k).label}</option>`).join('')}</select></div></div>`;
  if(r.kind==='crane_sling'){const opts=data.objects.filter(o=>o.id!==r.id).map(o=>`<option value="${o.id}">${o.name}</option>`).join('');special=`<div class="inspector-block"><h4>Eslinga procedural</h4><div class="kv"><span>Desde</span><select id="slingFrom"><option value="">—</option>${opts}</select></div><div class="kv"><span>Hasta</span><select id="slingTo"><option value="">—</option>${opts}</select></div></div>`;}
  $('#inspector').innerHTML=`<div class="kv"><span>Nombre</span><input id="objName" value="${esc(r.name)}"></div><div class="kv"><span>Modelo</span><select id="objAsset"><option value="">Placeholder</option>${assets}</select></div>${anims?`<div class="kv"><span>Animación</span><select id="objAnim"><option value="">Sin preview</option>${anims}</select></div>`:''}<div class="inspector-block"><h4>Transform</h4><div class="inspector-grid"><span></span><b>X</b><b>Y</b><b>Z</b>${numInput('Pos','position','x',r.transform.position.x)}${numInput('','position','y',r.transform.position.y)}${numInput('','position','z',r.transform.position.z)}${numInput('Rot°','rotation','x',THREE.MathUtils.radToDeg(r.transform.rotation.x))}${numInput('','rotation','y',THREE.MathUtils.radToDeg(r.transform.rotation.y))}${numInput('','rotation','z',THREE.MathUtils.radToDeg(r.transform.rotation.z))}${numInput('Esc','scale','x',r.transform.scale.x)}${numInput('','scale','y',r.transform.scale.y)}${numInput('','scale','z',r.transform.scale.z)}</div></div>${special}<div class="row"><button id="dupObj">Shift+D Duplicar</button><button id="delObj">Delete</button></div>`;
  $('#objName').onchange=e=>{r.name=e.target.value;queueSave();renderTree();};$('#objAsset').onchange=async e=>{r.assetId=e.target.value||null;r.animation=null;await instantiateRecord(r);selectRecord(r.id);queueSave();};$('#objAnim')?.addEventListener('change',e=>{r.animation=e.target.value||null;playAnimation(r.id,r.animation);queueSave();});document.querySelectorAll('.tr').forEach(el=>el.addEventListener('change',()=>{const v=+el.value;if(el.dataset.key==='rotation')r.transform.rotation[el.dataset.axis]=THREE.MathUtils.degToRad(v);else r.transform[el.dataset.key][el.dataset.axis]=v;applyTransform(selectedThree,r.transform);queueSave();}));$('#dupObj').onclick=duplicateSelected;$('#delObj').onclick=deleteSelected;
  if(r.kind==='buffer'){ $('#bufCount').onchange=e=>{r.meta.count=+e.target.value;refreshBufferVisual(r);queueSave();};document.querySelectorAll('.bufOff').forEach(el=>el.onchange=()=>{r.meta.offset[el.dataset.axis]=+el.value;refreshBufferVisual(r);queueSave();});$('#bufVisual').onchange=e=>{r.meta.visualKind=e.target.value;refreshBufferVisual(r);queueSave();}; }
  if(r.kind==='crane_sling'){const f=$('#slingFrom'),t=$('#slingTo');f.value=r.meta.fromRef||'';t.value=r.meta.toRef||'';f.onchange=()=>{r.meta.fromRef=f.value||null;refreshSling(r);queueSave();};t.onchange=()=>{r.meta.toRef=t.value||null;refreshSling(r);queueSave();};}
}
function esc(s){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));}

async function playAnimation(id,name){const obj=runtime.get(id);if(!obj)return;if(mixers.has(id))mixers.delete(id);if(!name)return;const clips=obj.userData.editorAnimations||[];const clip=clips.find(c=>c.name===name);if(!clip)return;const m=new THREE.AnimationMixer(obj);m.clipAction(clip).play();mixers.set(id,m);}

function renderAssetLibrary(){$('#assetLibrary').innerHTML=data.assets.map(a=>`<div class="asset-row"><span class="asset-name">${a.name}</span><small>${(a.animations||[]).length} anim</small><button data-del-asset="${a.id}">×</button></div>`).join('')||'<div class="muted">Todavía no cargaste modelos.</div>';document.querySelectorAll('[data-del-asset]').forEach(b=>b.onclick=()=>{const id=b.dataset.delAsset;if(data.objects.some(o=>o.assetId===id)&&!confirm('Hay objetos usando este modelo. ¿Quitar igual?'))return;data.assets=data.assets.filter(a=>a.id!==id);data.objects.filter(o=>o.assetId===id).forEach(o=>{o.assetId=null;instantiateRecord(o);});assetRuntime.delete(id);queueSave();renderAssetLibrary();renderInspector();});}
async function uploadModel(file){const id=uid('asset');await dbPut('model:'+id,file);const a={id,name:file.name,animations:[]};data.assets.push(a);try{await instantiateAsset(id);}catch(e){alert('No pude leer ese GLB/GLTF: '+e.message);}queueSave();renderAssetLibrary();renderInspector();}

function rebuildFloor(){floorGroup.clear();const w=data.floor.width,d=data.floor.depth,s=data.gridSize;for(let x=0;x<w;x++)for(let z=0;z<d;z++){const key=x+','+z;const tileId=data.floor.cells[key];const mat=new THREE.MeshStandardMaterial({color:tileId?0xffffff:0x343a40,side:THREE.DoubleSide});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(s,s),mat);mesh.rotation.x=-Math.PI/2;mesh.position.set((x-w/2+.5)*s,0,(z-d/2+.5)*s);mesh.userData.floorCell={x,z,key};floorGroup.add(mesh);if(tileId)applyTileTexture(mesh,tileId);} }
async function applyTileTexture(mesh,tileId){const blob=await dbGet('tile:'+tileId);if(!blob)return;const url=URL.createObjectURL(blob);textureLoader.load(url,tex=>{tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.colorSpace=THREE.SRGBColorSpace;mesh.material.map=tex;mesh.material.color.set(0xffffff);mesh.material.needsUpdate=true;URL.revokeObjectURL(url);});}
function renderTilePalette(){$('#tilePalette').innerHTML=data.tiles.map(t=>`<div class="tile-row"><div class="tile-thumb ${t.id===currentTileId?'active':''}" data-tile="${t.id}" title="${esc(t.name)}"></div><span>${esc(t.name)}</span></div>`).join('')||'<div class="muted">Cargá una textura para pintar.</div>';data.tiles.forEach(async t=>{const blob=await dbGet('tile:'+t.id);if(!blob)return;const el=document.querySelector(`[data-tile="${t.id}"]`);if(el){const u=URL.createObjectURL(blob);el.style.backgroundImage=`url(${u})`;el.onclick=()=>{currentTileId=t.id;eraseFloorMode=false;renderTilePalette();};}});}
async function uploadTile(file){const id=uid('tile');await dbPut('tile:'+id,file);data.tiles.push({id,name:file.name});currentTileId=id;queueSave();renderTilePalette();}

function renderCatalog(filter=''){const q=filter.toLowerCase();$('#objectCatalog').innerHTML=Object.entries(CATALOG).map(([group,items])=>{const shown=items.filter(i=>i[1].toLowerCase().includes(q)||i[0].includes(q));if(!shown.length)return'';return `<div class="catalog-group"><h3>${group}</h3><div class="catalog-grid">${shown.map(i=>`<button type="button" data-add-kind="${i[0]}">${i[1]}</button>`).join('')}</div></div>`;}).join('');document.querySelectorAll('[data-add-kind]').forEach(b=>b.onclick=()=>{addRecord(b.dataset.addKind);$('#objectDialog').close();});}

function addRoute(){const r={id:uid('route'),name:'Ruta '+(data.routes.length+1),vehicleAssetId:null,keyframes:[{id:uid('kf'),ref:'custom',transform:transformData()},{id:uid('kf'),ref:'custom',transform:{...transformData(),position:{x:4,y:0,z:0}}}]};data.routes.push(r);renderRoutes();selectRouteKeyframe(r.id,r.keyframes[0].id);queueSave();}
function renderRoutes(){const sel=$('#routeSelect');sel.innerHTML=data.routes.map(r=>`<option value="${r.id}">${r.name}</option>`).join('')||'<option value="">Sin rutas</option>';if(data.routes.length&&!sel.value)sel.value=data.routes[0].id;renderRouteEditor();redrawRoutes();}
function currentRoute(){return data.routes.find(r=>r.id===$('#routeSelect').value)||data.routes[0]||null;}
function renderRouteEditor(){const r=currentRoute();if(!r){$('#routeEditor').innerHTML='<div class="muted">Creá una ruta.</div>';return;}$('#routeSelect').value=r.id;const models=data.assets.map(a=>`<option value="${a.id}" ${r.vehicleAssetId===a.id?'selected':''}>${a.name}</option>`).join('');$('#routeEditor').innerHTML=`<div class="kv"><span>Nombre</span><input id="routeName" value="${esc(r.name)}"></div><div class="kv"><span>Modelo ghost</span><select id="routeAsset"><option value="">Placeholder autoelevador</option>${models}</select></div><div id="kfList">${r.keyframes.map((k,i)=>`<div class="route-kf" data-kf="${k.id}"><div class="route-kf-head"><b>Keyframe ${i+1}</b><button data-del-kf="${k.id}">×</button></div><select data-kf-ref="${k.id}">${DYNAMIC_REFS.map(([v,l])=>`<option value="${v}" ${k.ref===v?'selected':''}>${l}</option>`).join('')}</select><small>${k.ref==='custom'?'Mover/rotar la copia fantasma en viewport':'Se resolverá dinámicamente in-game'}</small></div>`).join('')}</div><div class="route-actions"><button id="addKf">＋ Keyframe</button><button id="delRoute">Eliminar ruta</button></div>`;$('#routeName').onchange=e=>{r.name=e.target.value;queueSave();renderRoutes();};$('#routeAsset').onchange=e=>{r.vehicleAssetId=e.target.value||null;queueSave();redrawRoutes();};$('#addKf').onclick=()=>{const prev=r.keyframes.at(-1);const k={id:uid('kf'),ref:'custom',transform:structuredClone(prev?.transform||transformData())};k.transform.position.x+=2;r.keyframes.push(k);queueSave();renderRouteEditor();redrawRoutes();};$('#delRoute').onclick=()=>{data.routes=data.routes.filter(x=>x.id!==r.id);queueSave();renderRoutes();};document.querySelectorAll('[data-kf-ref]').forEach(s=>s.onchange=()=>{const k=r.keyframes.find(x=>x.id===s.dataset.kfRef);k.ref=s.value;queueSave();renderRouteEditor();redrawRoutes();});document.querySelectorAll('.route-kf').forEach(el=>el.onclick=e=>{if(e.target.tagName==='SELECT'||e.target.tagName==='BUTTON')return;selectRouteKeyframe(r.id,el.dataset.kf);});document.querySelectorAll('[data-del-kf]').forEach(b=>b.onclick=()=>{if(r.keyframes.length<=2)return alert('Una ruta necesita al menos 2 keyframes.');r.keyframes=r.keyframes.filter(k=>k.id!==b.dataset.delKf);queueSave();renderRouteEditor();redrawRoutes();});}
let routeGhost=null,routeGhostInfo=null;
async function selectRouteKeyframe(routeId,kfId){const r=data.routes.find(x=>x.id===routeId),k=r?.keyframes.find(x=>x.id===kfId);if(!k||k.ref!=='custom')return;if(routeGhost){routeGroup.remove(routeGhost);disposeObject(routeGhost);}routeGhost=r.vehicleAssetId?await instantiateAsset(r.vehicleAssetId):placeholder('forklift');routeGhost.traverse(n=>{if(n.material){n.material=n.material.clone();n.material.transparent=true;n.material.opacity=.55;}});applyTransform(routeGhost,k.transform);routeGroup.add(routeGhost);routeGhostInfo={routeId,kfId};transform.attach(routeGhost);selectedId=null;selectedThree=routeGhost;$('#modeBadge').textContent='RUTA · KEYFRAME';document.querySelectorAll('.route-kf').forEach(el=>el.classList.toggle('active',el.dataset.kf===kfId));}
function syncRouteGhost(){if(!routeGhostInfo||transform.object!==routeGhost)return;const r=data.routes.find(x=>x.id===routeGhostInfo.routeId),k=r?.keyframes.find(x=>x.id===routeGhostInfo.kfId);if(k){k.transform=serializeTransform(routeGhost);queueSave();redrawRoutes(false);}}
transform.addEventListener('objectChange',syncRouteGhost);
function dynamicRefPosition(ref){if(ref==='custom')return null;const hotspot=data.objects.find(o=>o.meta?.refKey===ref||o.name===ref);if(hotspot)return runtime.get(hotspot.id)?.getWorldPosition(new THREE.Vector3())||null;return null;}
function redrawRoutes(rebuildGhost=true){[...routeGroup.children].forEach(c=>{if(c===routeGhost&&!rebuildGhost)return;routeGroup.remove(c);if(c!==routeGhost)disposeObject(c);});data.routes.forEach(r=>{const pts=r.keyframes.map(k=>k.ref==='custom'?new THREE.Vector3(k.transform.position.x,k.transform.position.y+.08,k.transform.position.z):dynamicRefPosition(k.ref)).filter(Boolean);if(pts.length>=2){const geo=new THREE.BufferGeometry().setFromPoints(pts);const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0x69c9ff}));routeGroup.add(line);pts.forEach(p=>{const s=new THREE.Mesh(new THREE.SphereGeometry(.12,8,6),new THREE.MeshBasicMaterial({color:0x69c9ff}));s.position.copy(p);routeGroup.add(s);});}});}

let saveTimer=null;function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(saveLocal,250);}function saveLocal(){data.gridSize=+$('#gridSize').value||1;data.camera={position:camera.position.toArray(),target:orbit.target.toArray()};localStorage.setItem(STORAGE_KEY,JSON.stringify(data));}
async function loadLocal(){const raw=localStorage.getItem(STORAGE_KEY);if(raw){try{data=Object.assign(defaultData(),JSON.parse(raw));}catch{data=defaultData();}}$('#gridSize').value=data.gridSize||1;$('#floorWidth').value=data.floor.width;$('#floorDepth').value=data.floor.depth;camera.position.fromArray(data.camera?.position||[18,20,22]);orbit.target.fromArray(data.camera?.target||[0,0,0]);updateGrid();rebuildFloor();for(const o of data.objects)await instantiateRecord(o);renderAll();}
function renderAll(){renderTree();renderLayers();renderInspector();renderAssetLibrary();renderTilePalette();renderCatalog();renderRoutes();}
function exportJson(){saveLocal();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='castorium-map.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function importJson(file){const txt=await file.text();const parsed=JSON.parse(txt);data=Object.assign(defaultData(),parsed);selectedId=null;transform.detach();objectGroup.clear();runtime.clear();$('#gridSize').value=data.gridSize||1;$('#floorWidth').value=data.floor.width;$('#floorDepth').value=data.floor.depth;updateGrid();rebuildFloor();for(const o of data.objects)await instantiateRecord(o);saveLocal();renderAll();}
function updateGrid(){scene.remove(grid);const s=+$('#gridSize').value||1;const size=Math.max(data.floor.width,data.floor.depth)*s*1.5;grid=new THREE.GridHelper(size,Math.round(size/s),0x7d8894,0x4b555f);grid.visible=$('#toggleGrid').classList.contains('active');scene.add(grid);data.gridSize=s;rebuildFloor();queueSave();}
function focusSelected(){const o=transform.object||selectedThree;if(!o)return;const box=new THREE.Box3().setFromObject(o),c=box.getCenter(new THREE.Vector3()),sz=Math.max(1,box.getSize(new THREE.Vector3()).length());orbit.target.copy(c);camera.position.copy(c.clone().add(new THREE.Vector3(sz,sz*.8,sz)));orbit.update();}

renderer.domElement.addEventListener('pointerdown',e=>{if(!floorPaint)return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(floorGroup.children,false)[0];if(hit){const key=hit.object.userData.floorCell.key;if(eraseFloorMode||!currentTileId)delete data.floor.cells[key];else data.floor.cells[key]=currentTileId;rebuildFloor();queueSave();}});

window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(e.shiftKey&&k==='d'){e.preventDefault();duplicateSelected();return;}if(e.altKey&&k==='h'){data.objects.forEach(o=>{o.visible=true;const ro=runtime.get(o.id);if(ro)ro.visible=data.layers[o.layer]!==false;});renderTree();queueSave();return;}if(k==='g'){transform.setMode('translate');$('#modeBadge').textContent='MOVER';}else if(k==='r'){transform.setMode('rotate');$('#modeBadge').textContent='ROTAR';}else if(k==='s'){transform.setMode('scale');$('#modeBadge').textContent='ESCALAR';}else if(['x','y','z'].includes(k)){axisLock=k.toUpperCase();transform.showX=k==='x';transform.showY=k==='y';transform.showZ=k==='z';}else if(k==='h'&&getSelected()){const r=getSelected();r.visible=false;runtime.get(r.id).visible=false;renderTree();queueSave();}else if(e.key==='Delete'){deleteSelected();}else if(k==='f'){focusSelected();}else if(k==='escape'){transform.showX=transform.showY=transform.showZ=true;axisLock=null;$('#modeBadge').textContent='OBJETO';}});

$('#addObject').onclick=()=>{$('#objectDialog').showModal();renderCatalog();};$('#objectSearch').oninput=e=>renderCatalog(e.target.value);$('#treeFilter').oninput=renderTree;$('#modelUpload').onchange=e=>e.target.files[0]&&uploadModel(e.target.files[0]);$('#tileUpload').onchange=e=>e.target.files[0]&&uploadTile(e.target.files[0]);$('#gridSize').onchange=updateGrid;$('#toggleGrid').onclick=e=>{e.currentTarget.classList.toggle('active');grid.visible=e.currentTarget.classList.contains('active');};$('#floorMode').onclick=e=>{floorPaint=!floorPaint;e.currentTarget.classList.toggle('active',floorPaint);orbit.enabled=!floorPaint;$('#modeBadge').textContent=floorPaint?'PINTAR PISO':'OBJETO';};$('#eraseFloor').onclick=()=>{eraseFloorMode=true;currentTileId=null;renderTilePalette();};$('#resizeFloor').onclick=()=>{data.floor.width=Math.max(1,+$('#floorWidth').value);data.floor.depth=Math.max(1,+$('#floorDepth').value);rebuildFloor();updateGrid();queueSave();};$('#newScene').onclick=()=>{if(!confirm('¿Vaciar la escena? Los modelos cargados se conservan en el navegador.'))return;const assets=data.assets,tiles=data.tiles;data=defaultData();data.assets=assets;data.tiles=tiles;objectGroup.clear();runtime.clear();floorGroup.clear();selectedId=null;transform.detach();rebuildFloor();renderAll();saveLocal();};$('#saveScene').onclick=()=>{saveLocal();alert('Guardado en este navegador.');};$('#exportScene').onclick=exportJson;$('#importScene').onchange=e=>e.target.files[0]&&importJson(e.target.files[0]);$('#focusSelected').onclick=focusSelected;$('#addRoute').onclick=addRoute;$('#routeSelect').onchange=()=>{renderRouteEditor();redrawRoutes();};

function resize(){const r=viewport.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();
function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();mixers.forEach(m=>m.update(dt));orbit.update();renderer.render(scene,camera);}animate();
loadLocal();
